# Linear algebra with Numpy



NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. It contains among other things:
 useful linear algebra, Fourier transform, and random number capabilities. 

In this section we will see how to:

- Manipulate matrices;
- Solve Matrix equations;
- Calculate Matrix inverse and determinants.
- Dot and Cross product
- Eigenvalues and Eigenvectors
- Norm
- Rank of Matrix
- SVD


## Manipulating matrices

It is straightforward to create a Matrix using Numpy. Let us consider the following as a examples:

$$
A = \begin{pmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{pmatrix}
$$

$$
B = \begin{pmatrix}
14 & -2 & 12\\
4 & 4 & 5\\
5 & 5 & 1
\end{pmatrix}
$$


First,  we need to import Numpy:

In [35]:
import numpy as np

Now we can define $A$:

In [36]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

In [37]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])

In [38]:
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [39]:
B

matrix([[14, -2, 12],
        [ 4,  4,  5],
        [ 5,  5,  1]])

In [40]:
A.ndim 

2

In [41]:
B.ndim

2

We can obtain the following straightforwardly:

- $5A$ (or any other scalar multiple of $A$);
- $A ^ 3$ (or any other exponent of $A$);
- $A + B$;
- $A - B$;
- $AB$

In [42]:
5 * A

matrix([[25, 30, 10],
        [20, 35, 95],
        [ 0, 15, 60]])

In [9]:
A ** 3

matrix([[ 557, 1284, 3356],
        [ 760, 2305, 6994],
        [ 288, 1074, 3519]])

In [43]:
A + B

matrix([[19,  4, 14],
        [ 8, 11, 24],
        [ 5,  8, 13]])

In [44]:
A - B

matrix([[ -9,   8, -10],
        [  0,   3,  14],
        [ -5,  -2,  11]])

In [45]:
A * B

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

## Tranpose

In [46]:
A.T

matrix([[ 5,  4,  0],
        [ 6,  7,  3],
        [ 2, 19, 12]])

In [47]:
A

matrix([[ 5,  6,  2],
        [ 4,  7, 19],
        [ 0,  3, 12]])


---

## Solving Matrix equations



Let us illustrate that with:
$$5x_1 + 6x_2 + 2x_3 = -1$$$$4x_1 + 7x_2 + 19x_3 = 2$$$$0x_1 + 3x_2 + 12x_3 = 1$$
 Given the above system of equations we can represent the equations in matrix form as below 

$$
A = \begin{bmatrix}
5 & 6 & 2\\
4 & 7 & 19\\
0 & 3 & 12
\end{bmatrix}
$$


$$
b = \begin{bmatrix}
-1\\
2\\
1 
\end{bmatrix}
$$


$$
x = \begin{bmatrix}
x_1\\
x_2\\
x_3 
\end{bmatrix}
$$

We can use Numpy to (efficiently) solve large systems of equations of the form:

$$Ax=b$$
$$\Rightarrow x=A^{-1}b$$

In [48]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
b = np.matrix([[-1], [2], [1]])

We use the `linalg.solve` command:

In [49]:
x = np.linalg.solve(A, b)
x

matrix([[ 0.45736434],
        [-0.62790698],
        [ 0.24031008]])

We can verify our result:

In [51]:
 A.x #Formula to Verify           

matrix([[-1],
        [ 2],
        [ 1]])



## Matrix inversion and determinants

Computing the inverse of a matrix is straightforward:
$A^{-1}A=\mathbb{1}$:

In [54]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,10]])
Ainv = np.linalg.inv(A)
Ainv

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

We can verify by:

In [55]:
A*Ainv# Formula To Verify

matrix([[1.00000000e+00, 0.00000000e+00, 1.11022302e-16],
        [0.00000000e+00, 1.00000000e+00, 2.22044605e-16],
        [8.88178420e-16, 0.00000000e+00, 1.00000000e+00]])

The above might not look like the identity matrix but if you look closer you see that the diagonals are all `1` and the off diagonals are a **very** small number (which from a computer's point of view is `0`).

To calculate the determinant:

In [56]:
np.linalg.det(A)

-2.9999999999999996

##Dot and Cross Multiplication 

The resultant of scalar product/dot product of two vectors is always a scalar quantity. Consider two vectors a and b. The scalar product is calculated as the product of magnitudes of a, b, and cosine of the angle between these vectors.


The resultant of vector product/cross product of two vectors is always a vector quantity. Consider two vectors a and b. The vector product is calculated as the product of magnitudes of a, b, and sine of the angle between these vectors.

In [57]:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])
B = np.matrix([[14, -2, 12],
               [4, 4, 5],
               [5, 5, 1]])

In [58]:
np.dot(A,B)

matrix([[104,  24,  92],
        [179, 115, 102],
        [ 72,  72,  27]])

In [59]:
np.cross(A,B)

array([[ 76, -32, -94],
       [-41,  56, -12],
       [-57,  60, -15]])

In [65]:
C=np.matrix([[2,4,3],[4,1,8],[3,8,2]])
if (C==C.T).all():#What should be the condition to check for symmetric matrix
  print("symmetric")

symmetric


##Normal Matrix Multiplication


In [27]:
 np.multiply(A,B)

matrix([[ 70, -12,  24],
        [ 16,  28,  95],
        [  0,  15,  12]])

##Eigenvalues and Eigenvectors
Eigen vector of a matrix A is a vector represented by a matrix X such that when X is multiplied with matrix A, then the direction of the resultant matrix remains same as vector X.

Eigenvalue is the scalar that is used to transform (stretch) an Eigenvector.


In [28]:
np.linalg.eig(A)

(array([-1.03997841,  6.80080283, 18.23917558]),
 matrix([[ 0.6664281 ,  0.91899137,  0.42824655],
         [-0.72658863,  0.34150445,  0.81440731],
         [ 0.16716024, -0.19705222,  0.39159371]]))

##Norms
Distance of the vector from the origin.

L1 norm = $||x||_1 = \sqrt{\sum\nolimits_{i = 1}^{n}{|x_i|}}$

L2 norm = $||x||_2 = \sqrt{\sum\nolimits_{i = 1}^{n}{(x_i)^2}}$

In [66]:
D=np.matrix([[1,2,3],[4,5,6]])
np.linalg.norm(D)# L2 Norm by default

9.539392014169456

In [67]:
np.linalg.norm(D,1)#L1 Norm

9.0

In [68]:
np.linalg.norm(D,axis=0) # Norm according to column

array([4.12310563, 5.38516481, 6.70820393])

In [69]:
np.linalg.norm(D,axis=1) # Norm according to row

array([3.74165739, 8.77496439])

## Rank of Matrix
The rank of the matrix refers to the number of linearly independent rows or columns in the matrix

In [33]:
np.linalg.matrix_rank(D)

2

## Single Value Decomposition (SVD)

Singular Value Decomposition (SVD) of a matrix is a factorization of that matrix into three matrices. $A=UDV^T$, where

D is a diagonal matrix, with d=rank(A) non-zero elements

The fist d rows of U are orthogonal basis for col(A)

The fist d rows of V are orthogonal basis for row(A)

In [70]:
np.linalg.svd(D)

(matrix([[-0.3863177 , -0.92236578],
         [-0.92236578,  0.3863177 ]]),
 array([9.508032  , 0.77286964]),
 matrix([[-0.42866713, -0.56630692, -0.7039467 ],
         [ 0.80596391,  0.11238241, -0.58119908],
         [ 0.40824829, -0.81649658,  0.40824829]]))



## Summary

In this tutorial we have seen how to using Numpy:

- Manipulate matrices;
- Solve linear systems;
- Compute Matrix inverses and determinants.
- Dot and Cross product
- Eigenvalues and Eigenvectors
- Norm
- Rank of Matrix
- SVD

This again just touches on the capabilities of Numpy.

